# Assessment overview

The primary form of assessment in the course will be i) **3** regular Unit Exams and ii) a required, semi-cumulative Final Exam that combines information from Unit 4 **and the previous units**.

<!-- Each test will cover about 4 1/2 weeks of materials. -->

Approximately **75%** of your grade will be based on these tests.  See the course point breakdown on Canvas for the exact number.

Other forms of assessment include

* Short assignments and problem sets completed out of class
* In-class participation through TopHat
* In-class worksheets, submitted as photos via TopHat

<!-- (All in-class assignments will remain open for 24 hours) -->


<!-- * **Exam re-works**  that allow you to review the tests (these count as assignments and do not add points to your exam) -->
<!-- * Numerous short "micro-quizzes" within lectures to build vocab and test comprehension -->

As detailed elsewhere in the syllabus a portion of each of these individuals components of your grade will be dropped to accommodate illness or other personal issues.  You do not need to submit information (e.g. from a doctor) when you miss an assignment or test.

Sometimes assignments or questions will be marked as based partially or entirely scored for participation or completion.  These assignments ARE required - "*for participation*" does NOT mean optional. 

Occasionally, fully optional assignments worth 0 points will be released - these will be clearly marked as worth 0 points and for practice only.

The syllabus will take you step-by-step through all the policies related to these elements of the course.