# Goals

The goal of Our Changing World is to expand your understanding of the key processes related to how biological systems evolve and change, and how human activities modify them.  The course will also introduce you to how scientists study biological changes at different scales, from DNA to the entire biosphere (Links to an external site.).

 

## Concepts: From Mutations to the Biosphere

Key biology concepts covered this semester will be

* DNA and how mutations occur (Molecular biology)
* How mutations spread through a population (Population genetics)
* How genomes (Links to an external site.) change over time (Genomics)
* Phylogenetic (Links to an external site.) trees (Phylogenetics)
* How species change over time (Evolution & Natural selection)
* For formation and origin of new species (Speciation)
* The ecology of species & populations (Biogeography & population ecology)
* The ecology of groups of interacting organisms (Community ecology)
* Ecosystem ecology
* Biogeochemical cycling
 


## Population biology: natural selection, speciation, phylogenetics & ecology

Throughout the course we will emphasize the evolutionary background of the topics we discuss. During the second half of the course we will specifically focus on the biology of populations and the dynamics of natural selection, the origin of species (speciation), the evolutionary relationships among species (phylogenetics (Links to an external site.)), and the process of population growth and regulation which are key to understanding evolution (population ecology).



 

## Species interactions & Community ecology

We will finish the semester learning about species interactions, such as predators versus their prey, and the structure of communities made up of multiple interacting species.



## Skills: Doing & Communicating Science

Our Changing World will develop your skills as a critical consumer of science. By the end of the course you should not only understand the conceptual material presented in the book but also be able to critically approach new scientific material such as scientific talks and journal articles. We will practice assessing scientific results, understanding figures, and presenting and analyzing data.  Throughout the course we will therefore discuss

* How science is conducted & communicated
* Application of the scientific method
* How experiments & observational studies are conducted
* Understanding scientific figures
* Data analysis Statistics
* Scientific inference