# Lectures & Mini-quiz questions

"Quizzes" on Canvas will be used both to prepare you for an upcoming lecture and to review material after the lecture.
 
I will use the term "quizzes" because this is the term Canvas uses, but they may just be a single question.

I will refer to these variously "mini-quizzes", "vocab builders", "concept builders" etc. to indicate their purpose.

These "quiz" questions on Canvas are generally easier than questions on the test and are mostly designed to reinforce vocab and basic data interpretation.

Until the 1st test all "quiz" questions remain open so that those who joined the class later can catch up. 

Questions related to an upcoming lecture will be released on Friday by 5:00 PM and due at noon the day of the lecture.  This will be based on assigned readings.  

Question that are following up on a lecture will be due by noon the day of the following lecture.

Therefore, you can expect to have Canvas quiz questions due both Tuesday and Thursday at noon.  Questions due Tuesday will either be following up from the previous Thursday's lecture or have been assigned Friday to prepare you for the next lecture.  Questions due Thursday will either have been assigned the previous Friday (lecture preparation) or Tuesday (followup).

Quizzes will be graded but you will have multiple attempts to take each quiz and opportunities to update your answers.   If a question only allows you to answer once please contact me and I will change the settings.

Questions will normally be set to show the key only after the question has closed.  Questions opened on the Tuesday prior to a test will be set to show the key after you have submitted your answer.  If this does not occur please contact me so I can change the settings.

As detailed elsewhere in the syllabus a portion of these mini-quiz questions will be dropped (e.g., to accommodate illness).

Readings to prepare for lectures will be released the preceding Friday at 5:00 pm. 