# Point allocation {#points}

<!-- The course contains 4 units and each unit has a test; there will also be a cumulative final.   -->

<!-- Your lowest scores will be automatically dropped as detailed elsewhere in the syllabus.  (They will not all be dropped until final grades are calculated, so your grade reported by Canvas will be an underestimate with regards to tests!) -->

<!-- The 3 tests which count towards your grade and the final will contribute ~75% of your final grade.  Each mini-test will therefore be worth about 16.5% of your grade.  -->

<!-- Participation, test revisions, other assignments, and quizzes will contribute ~25%.   -->

<!-- You can view the point breakdown and a summary of related policies [here]().  Commenting is enabled; feel free to post questions. -->

```{r, echo = F}
url. <- ""
knitr::include_url(url.)
```


```{r, echo = F}
url.  <- "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Triple_beam_balance3.JPG/240px-Triple_beam_balance3.JPG"
knitr::include_url(url.)
```


<!-- ```{r fig.margin = TRUE, fig.cap = "", fig.width=3.5, fig.height=3.5, cache=TRUE, message=FALSE} -->
<!-- library(ggpubr) -->
<!-- point_breakdown$`% of final grade` <- gsub("%","",point_breakdown$`% of final grade`) -->
<!-- point_breakdown$`% of final grade` <- as.numeric(point_breakdown$`% of final grade`) -->
<!-- names(point_breakdown)[4] <- "percent" -->
<!-- #names(point_breakdown)[2] <- "Item" -->
<!-- point_breakdown$label <- "" -->
<!-- ggpie(data = point_breakdown, -->
<!--       x = "percent", -->
<!--       label = "Item", -->
<!--       fill = "Item") -->
<!-- ``` -->

<!-- ```{r, eval = T, echo = F} -->
<!-- knitr::kable(point_breakdown[, -ncol(point_breakdown)]) -->
<!-- ``` -->


<!-- Notes:  -->

<!-- 1. "*" = the value in the "Number" column is an approximation.  Final numbers of assignments to be determined. -->
<!-- 1. Each midterm covers ~7 lectures -->
<!-- 1. The Unit 4 exam given along with final -->
<!-- 1. The Unit 4 exam will cover lectures which occur between the 3rd midterm and the final. -->
<!-- 1. If higher, your final exam can replace your lowest midterm from units 1-3 -->
<!-- 1. There will be no extra credit offered. -->



<!-- The point breakdown can be viewed as a spreadsheet here -->
<!-- https://docs.google.com/spreadsheets/d/1qfd8oX_JVzHgCqkIV2VZlBqWRmqUaftbQ4U_DBH33yw/edit?usp=sharing -->
