# Course communication - Email and Canvas messages {#email_and_canvas_msg}

Announcements to the whole course via Canvas will occur typically on **Friday** afternoons.  Other communication related to course administration will also occur via Canvas messages.  It is your responsibility to regularly check Canvas messages to stay abreast of the course.

Your can message me on Canvas or email me at nlb24 at pitt.edu.

Please include "OCW" (Our Changing World) as the 1st thing in your email subject line with an informative bit of information as the "...". e.g. "Subect: OCW - problem accessing TopHat".


If you use another email service as your primary email (eg GMail) please set your Pitt email to forward there. 

For info on forwarding your Pitt email to your personal account follow this link: [https://bit.ly/2Riz7dx](https://bit.ly/2Riz7dx)

I try to answer all emails received on weekdays before 5 pm within 24-36 hrs.  Emails received after 5 pm will be answered at the earliest the following morning.  Emails received on the weekend will be answered Monday. 


Please consult this syllabus before asking questions about course policies and the schedule, and refer to relevant information such as URLs, subject headings or dates. Screengrabs are super helpful. If the entire answer to your question can be found in the syllabus I will likely respond by saying something like

> "*This is in the syllabus, Cheers, Dr. B.*". 

Questions relevant to the whole class may be re-posted (with identifying details removed) to Canvas.

