# Grade and exam inquiries

If you are concerned that your grade has be miscalculated, a key was wrong, or that there were multiple correct answers please fill out a **Grade Inquiry Form**.   A link will be provided when the form is ready for us.  

I will briefly evaluate all submitted forms to determine if there is an issue that requires immediate attention.  ***Otherwise, the resolution of the issue will not occur until grades are calculated.*** 

*AFTER* final grades have been calculated I will determine if the resolution of issues on a Grade Inquiry forms will impact your final grade.

If your final grade will potentially be impacted I will fully evaluate your inquiry and notify you via email regarding its resolution.

If you did not receive information about your inquiry it means your final grade would not have been impacted. 

Inquires about exam are due one week after its key is released.  

Unless you submitted an Exam Inquiry Form I will not discuss specific test questions during office hours.

Inquiries about the final exam will not be addressed until the next semester.