# Office hours

## INSTRUCTOR OFFICE HOURS

**MONDAY**: 11-12 pm.
[Zoom](https://pitt.zoom.us/j/94009208405): https://pitt.zoom.us/j/94009208405
Password: "puppies" (all caps)

**WEDNESDAY**: 11-12 pm
[Zoom](https://pitt.zoom.us/j/94009208405): https://pitt.zoom.us/j/94009208405
Password: "puppies" (all caps)

**Other days:** By [appointment](calendly.com/brouwern): [calendly.com/brouwern](calendly.com/brouwern)

Office hours will be offered initially only via Zoom.  After the first 2 weeks of the semester I evaluate if I will begin in-person office hours on Wednesdays.



## UTA OFFICE HOURS

UTA office hours will be posted by the beginning of the 2nd week of lectures.  



## Individual appointments

I'm available for individual 15 minute appointments 10 am to noon on Tuesdays, Thursdays and Fridays.  Schedule these appointments via [Calendely](https://calendly.com/brouwern/15min):[https://calendly.com/brouwern/15min](https://calendly.com/brouwern/15min)

If office hours or available times for appointments do not work for you, please email me to coordinate a different meeting time.
