# Office hours tips

Some guidelines for office hours:

1. **Don't be intimidated by office hours.**  One of my favorite parts of my job is talking with students one-on-one.
1. **Be prepared for office hours.**  Come with specific questions related to slides, figures, etc.  But if you just want to listen what I'm talking about with other students, that's totally cool.
1. **Office hours are for everyone.** If multiple people show up I will alternate between them to answer their questions. If I feel I have answered your main questions I may ask that we table our discussion to cover other questions.

**Note:** *During finals week I do not hold office hours and am not available for appointments.*

During office hours, specific questions are better than vague ones, even if it's just "*I specifically don't understand Fig. 4 in this chapter*."

A question like "*I don't understand natural selection*" is harder for me to work with.

I'm also happy to talk about study strategies, classes you might want to take, research opportunities etc.

 