# How to succeed in this course

Below are some suggestions on how to take on this challenge.

1. **Have confidence** – you can learn the material!  
1. Read the assigned readings before the lectures. 
1. Read slowly and thoroughly, but **taking notes isn't necessary**. Familiarize yourself with the vocabulary terms and look up unfamiliar words.
1. Read the **figure caption**s in the book and walk through the illustrations. 
1. I recommend taking notes by hand with pen and paper or on a tablet during lecture.
1. If possible, print out the slides and fill in key information.
1. Review your notes at least briefly after a short time after the lecture.
1. As soon as possible, fill in any gaps with information from the book, other suggested study resources, re-watching the appropriate video, information from the discussion boards or office hours, etc.
1. Study with a partner or small study group, perhaps using Zoom.
1. Attend office hours, even if it's just to listen to what other people are asking.
1. Try not to study for long, uninterrupted periods of time without a significant break.
Two half-hour or 45-minute study sessions are better than one marathon 1-2 hour session.
1. Ask for help when necessary - before you fall behind. Go to office hours as often as necessary.   The UTAs and I are here to help!