# Exam study guides

When lecturing I try to minimize diversions and content that will not be assessed on an exam.  In my lectures I will flag information as "background" or "not on the test" when necessary.

In general I don't require you to memorize numbers or dates, and any exceptions will be clearly marked.

I also don't require you to remember the names of people (e.g. famous scientists) or events in their lives.  The only standing exception to this is Charles Darwin - any time I talk about Darwin's life its important.  Any other exception will be clearly noted. 

In contrast, vocab is very important.  Unless stated otherwise all vocab is important and could be on the test.


## Study guides

Given the above, when preparing for the tests the best study guides are your notes from.

Exam study guides MAY be made available before each test but these study guides are in no way complete, comprehensive, or representative. 

If they are available, I'll let you know. 

If available, they are most useful to look over AFTER you have thoroughly reviewed all your other class materials.