# Exam grading policies

## Number of tests and calculation of final grade

* There will be 3 Unit Exams and 1 Final Exam administered throughout the semester. 
* The final exam will be semi-cumulative.
* Your best 2 scores on of the 3 Unit Exams will be automatically dropped when grades are calculated at the end of the semester.
* Makeup exams cannot be given.
* If you are unable to take a unit test for ANY reason it will be counted zero.
* If you miss just 1 test, that score will not contribute to your final grade - no worries.
* You can take **one** of the 3 regular unit exams remotely via Zoom if you contact me beforehand.
* You must take the final exam in-person


<!--  * Additionally, your score on the final can replace your 2nd lowest score, if the final is higher.  If your score on the final is lower it does not lower your previous test score. -->
<!-- * Your grade will therefore be based on your 4 best scores plus the final; 1 of those 4 can be modified by the final, so the final can count twice. -->
<!-- * If you miss 2 tests, 1 will be dropped and the 2nd can be replaced by your score on the final. -->
<!-- * If you miss 3 tests, the 3rd zero will remain a zero.  If this occurs please contact your advisers to consider your options. -->


## Test length & format

NOTE: the following policies are provisional and may be adjusted as needed to optimize test length and how to implement the "buffer question" policy in Canvas.

* Exams will be scored out of 45 points.   However, there will be at least 47 points worth of questions on the test.  Each exam therefore will effectively contain 2 or "**buffer points**" that you can miss without harming your grade. 
* The final exam will also contain buffer points.

<!-- * The maximum score on a Unit Exam will always be capped at 45/45. If there are 47 points on a test and you get all 47 questions correct your score will be 100%.  -->
<!-- * No extra credit will be offered on tests; the maximum score on a test will be 100%. -->
 

## Test question formats

* Test questions will frequently be multiple choice.  Keyword: "*frequently*" - there will other types of questions too!
* Most exams will have at least one question requiring a numeric calculation.  
* Other common forms of questions are fill in the blank, dropdowns, or matching. 
* There will likely NO True/False questions on tests.
* For fill-in-the-blank questions, spelling errors will result in 0 points.  No partial credit will be given.